### ISSUE TITLE
[demo] add link to create a test fixture in GitHubRepository

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/getrector.org#155]
## Idea

- run demo - https://getrector.org/demo
- it produces some false positive :cry: 
- clink on "Create Pull-Requets Test" button
- it will find the responsible rule, e.g. `ChangeArrayPushToArrayAssignRector`
- it will open pull-request on GitHub
- located fixture in `hangeArrayPushToArrayAssignRectorTest` in `Fixtures` directory

:+1:

**Comment by JanMikes** [comment]
I like the idea :-)

**Comment by TomasVotruba** [comment]
Great :)

I have no idea how to create PR with specific content... URL content `?fillWith=...` would be enough, but not sure if GitHub works this way.

**Comment by JanMikes** [comment]
There are 2 ways of creating PR that comes in my mind right now:

- **Github API** - that would be complicated imo, it is the way we used in Rector CI and you would have to create blob file, reference, pr -> it is like 4 api calls
- **git repository + Github CLI** - `git commit && git push` and then create PR via CLI, but i did not have opportunity to use the GH CLI yet, so i am not sure

There are few challenges, since getrector.org runs in one Docker container, then the demo code runs in other container and we are passing data around via volumes + PR would go to rectorphp/rector repository and we do not have access to any repository inside of Docker, we would have to figure out how to achieve it - it is definitely doable in non-drastic way, but first we need to make some analysis or proof of concepts :-) i like this task and i could try it out, but now  im working hard on finishing rector's parallel feature, maybe next week if we give prio to this.

**Comment by TomasVotruba** [comment]
Maybe I should rephrase, we don't need to create PR itself. They'll have to click on "Create pull request" themselves.

We need to let people open pull request with predefined content.

**Comment by JanMikes** [comment]
Ah, i see now. That scenario seems to be "a bit" difficult to me 😄 i will think about it.

**Comment by TomasVotruba** [comment]
I got it... Basically it's just a link to create new file.

Same as I have on my website. Instead of edit, there will be just "new file" with content

**Comment by TomasVotruba** [comment]
Done :+1:
